// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;


RcppExport SEXP _rcpp_module_boot_stan_fit4IPM_ICchinook_pp_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4IPM_LCRchum_pp_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4IPM_SMS_np_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4IPM_SMS_pp_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4IPM_SMaS_np_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4IPM_SS_np_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4IPM_SS_pp_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4IPM_SSpa_pp_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4RR_SS_np_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4RR_SS_pp_mod();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_stan_fit4IPM_ICchinook_pp_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4IPM_ICchinook_pp_mod, 0},
    {"_rcpp_module_boot_stan_fit4IPM_LCRchum_pp_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4IPM_LCRchum_pp_mod, 0},
    {"_rcpp_module_boot_stan_fit4IPM_SMS_np_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4IPM_SMS_np_mod, 0},
    {"_rcpp_module_boot_stan_fit4IPM_SMS_pp_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4IPM_SMS_pp_mod, 0},
    {"_rcpp_module_boot_stan_fit4IPM_SMaS_np_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4IPM_SMaS_np_mod, 0},
    {"_rcpp_module_boot_stan_fit4IPM_SS_np_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4IPM_SS_np_mod, 0},
    {"_rcpp_module_boot_stan_fit4IPM_SS_pp_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4IPM_SS_pp_mod, 0},
    {"_rcpp_module_boot_stan_fit4IPM_SSpa_pp_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4IPM_SSpa_pp_mod, 0},
    {"_rcpp_module_boot_stan_fit4RR_SS_np_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4RR_SS_np_mod, 0},
    {"_rcpp_module_boot_stan_fit4RR_SS_pp_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4RR_SS_pp_mod, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_salmonIPM(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
