# Generated by rstantools.  Do not edit by hand.

# names of stan models
stanmodels <- c("IPM_ICchinook_pp", "IPM_LCRchum_pp", "IPM_SMS_np", "IPM_SMS_pp", "IPM_SMaS_np", "IPM_SS_np", "IPM_SS_pp", "RR_SS_np", "RR_SS_pp")

# load each stan module
Rcpp::loadModule("stan_fit4IPM_ICchinook_pp_mod", what = TRUE)
Rcpp::loadModule("stan_fit4IPM_LCRchum_pp_mod", what = TRUE)
Rcpp::loadModule("stan_fit4IPM_SMS_np_mod", what = TRUE)
Rcpp::loadModule("stan_fit4IPM_SMS_pp_mod", what = TRUE)
Rcpp::loadModule("stan_fit4IPM_SMaS_np_mod", what = TRUE)
Rcpp::loadModule("stan_fit4IPM_SS_np_mod", what = TRUE)
Rcpp::loadModule("stan_fit4IPM_SS_pp_mod", what = TRUE)
Rcpp::loadModule("stan_fit4RR_SS_np_mod", what = TRUE)
Rcpp::loadModule("stan_fit4RR_SS_pp_mod", what = TRUE)

# instantiate each stanmodel object
stanmodels <- sapply(stanmodels, function(model_name) {
  # create C++ code for stan model
  stan_file <- if(dir.exists("stan")) "stan" else file.path("inst", "stan")
  stan_file <- file.path(stan_file, paste0(model_name, ".stan"))
  stanfit <- rstan::stanc_builder(stan_file,
                                  allow_undefined = TRUE,
                                  obfuscate_model_name = FALSE)
  stanfit$model_cpp <- list(model_cppname = stanfit$model_name,
                            model_cppcode = stanfit$cppcode)
  # create stanmodel object
  methods::new(Class = "stanmodel",
               model_name = stanfit$model_name,
               model_code = stanfit$model_code,
               model_cpp = stanfit$model_cpp,
               mk_cppmodule = function(x) get(paste0("rstantools_model_", model_name)))
})
